import json
import sys
import os

sys.path.insert(0, os.path.abspath('scratch'))
import generate_continuous_200 as gen_200

all_200 = gen_200.all_200
print(f"Loaded {len(all_200)} items.")

html_lines = []
html_lines.append('<!DOCTYPE html>')
html_lines.append('<html lang="ko">')
html_lines.append('<head>')
html_lines.append('  <meta charset="UTF-8">')
html_lines.append('  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">')
html_lines.append('  <title>2027 KICE 전문상담 1~200 핵심 표제어 마스터 (카드뒤집기·별표암기·아이케어 다크)</title>')
html_lines.append('  <style>')
html_lines.append('    @page {')
html_lines.append('      size: A4 portrait;')
html_lines.append('      margin: 12mm 10mm 12mm 10mm;')
html_lines.append('    }')
html_lines.append('    html, body, div, table, thead, tbody, tr, th, td, p, h1, h2, h3, span, button, a, input, label {')
html_lines.append('      box-sizing: border-box;')
html_lines.append('      margin: 0;')
html_lines.append('      padding: 0;')
html_lines.append('    }')
html_lines.append('    body {')
html_lines.append('      font-family: "Malgun Gothic", "맑은 고딕", "Apple SD Gothic Neo", sans-serif;')
html_lines.append('      background: #0f1117;')
html_lines.append('      color: #e2e8f0;')
html_lines.append('      line-height: 1.65;')
html_lines.append('      padding: 16px 12px;')
html_lines.append('      -webkit-font-smoothing: antialiased;')
html_lines.append('      touch-action: manipulation;')
html_lines.append('    }')
html_lines.append('    .app-header {')
html_lines.append('      max-width: 1240px;')
html_lines.append('      margin: 0 auto 16px auto;')
html_lines.append('      background: #161a23;')
html_lines.append('      color: #f1f5f9;')
html_lines.append('      padding: 16px 20px;')
html_lines.append('      border-radius: 12px;')
html_lines.append('      border: 1px solid #2d3748;')
html_lines.append('      display: flex;')
html_lines.append('      justify-content: space-between;')
html_lines.append('      align-items: center;')
html_lines.append('      flex-wrap: wrap;')
html_lines.append('      gap: 12px;')
html_lines.append('      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);')
html_lines.append('    }')
html_lines.append('    .bar-title {')
html_lines.append('      font-size: 1.15rem;')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      display: flex;')
html_lines.append('      align-items: center;')
html_lines.append('      gap: 8px;')
html_lines.append('    }')
html_lines.append('    .bar-sub {')
html_lines.append('      font-size: 0.85rem;')
html_lines.append('      color: #94a3b8;')
html_lines.append('      margin-top: 3px;')
html_lines.append('    }')
html_lines.append('    .btn-group {')
html_lines.append('      display: flex;')
html_lines.append('      gap: 8px;')
html_lines.append('      align-items: center;')
html_lines.append('      flex-wrap: wrap;')
html_lines.append('    }')
html_lines.append('    .btn-action {')
html_lines.append('      background: #1e2536;')
html_lines.append('      color: #e2e8f0;')
html_lines.append('      border: 1px solid #334155;')
html_lines.append('      padding: 8px 14px;')
html_lines.append('      border-radius: 8px;')
html_lines.append('      font-size: 0.9rem;')
html_lines.append('      font-weight: 700;')
html_lines.append('      cursor: pointer;')
html_lines.append('      text-decoration: none;')
html_lines.append('      display: inline-flex;')
html_lines.append('      align-items: center;')
html_lines.append('      gap: 5px;')
html_lines.append('      font-family: inherit;')
html_lines.append('      transition: all 0.2s;')
html_lines.append('    }')
html_lines.append('    .btn-action:hover {')
html_lines.append('      background: #2d3748;')
html_lines.append('    }')
html_lines.append('    .btn-active {')
html_lines.append('      background: #fbbf24 !important;')
html_lines.append('      color: #0f1117 !important;')
html_lines.append('      border-color: #f59e0b !important;')
html_lines.append('      font-weight: 800;')
html_lines.append('    }')
html_lines.append('    .btn-star-filter {')
html_lines.append('      color: #fbbf24;')
html_lines.append('      border-color: #d97706;')
html_lines.append('    }')
html_lines.append('    .main-container {')
html_lines.append('      max-width: 1240px;')
html_lines.append('      margin: 0 auto;')
html_lines.append('    }')
html_lines.append('    .table-container {')
html_lines.append('      background: #11141d;')
html_lines.append('      border: 1.5px solid #2d3748;')
html_lines.append('      border-radius: 10px;')
html_lines.append('      box-shadow: 0 4px 24px rgba(0, 0, 0, 0.6);')
html_lines.append('      overflow-x: auto;')
html_lines.append('      -webkit-overflow-scrolling: touch;')
html_lines.append('    }')
html_lines.append('    .table-info-bar {')
html_lines.append('      background: #161b26;')
html_lines.append('      border-bottom: 2px solid #d97706;')
html_lines.append('      padding: 10px 16px;')
html_lines.append('      display: flex;')
html_lines.append('      justify-content: space-between;')
html_lines.append('      align-items: center;')
html_lines.append('      font-size: 0.9rem;')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      flex-wrap: wrap;')
html_lines.append('      gap: 8px;')
html_lines.append('    }')
html_lines.append('    table {')
html_lines.append('      width: 100%;')
html_lines.append('      border-collapse: collapse;')
html_lines.append('      font-family: "Malgun Gothic", "맑은 고딕", "Apple SD Gothic Neo", sans-serif;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      background: #11141d;')
html_lines.append('    }')
html_lines.append('    thead {')
html_lines.append('      background: #161a24;')
html_lines.append('      position: sticky;')
html_lines.append('      top: 0;')
html_lines.append('      z-index: 20;')
html_lines.append('    }')
html_lines.append('    th {')
html_lines.append('      background: #161a24;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      border: 1px solid #283042;')
html_lines.append('      padding: 10px 8px;')
html_lines.append('      font-weight: 800;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      text-align: center;')
html_lines.append('      letter-spacing: -0.2px;')
html_lines.append('    }')
html_lines.append('    td {')
html_lines.append('      border: 1px solid #222938;')
html_lines.append('      padding: 9px 12px;')
html_lines.append('      vertical-align: top;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      line-height: 1.6;')
html_lines.append('      color: #e2e8f0;')
html_lines.append('    }')
html_lines.append('    tr:nth-child(even) {')
html_lines.append('      background: #141822;')
html_lines.append('    }')
html_lines.append('    tr:nth-child(odd) {')
html_lines.append('      background: #10131b;')
html_lines.append('    }')
html_lines.append('    tr:hover {')
html_lines.append('      background: #1e2433;')
html_lines.append('    }')
html_lines.append('    .td-star-num {')
html_lines.append('      width: 60px;')
html_lines.append('      text-align: center;')
html_lines.append('      white-space: nowrap;')
html_lines.append('    }')
html_lines.append('    .star-btn {')
html_lines.append('      background: transparent;')
html_lines.append('      border: none;')
html_lines.append('      font-size: 1.15rem;')
html_lines.append('      cursor: pointer;')
html_lines.append('      color: #64748b;')
html_lines.append('      line-height: 1;')
html_lines.append('      padding: 2px;')
html_lines.append('      transition: transform 0.15s;')
html_lines.append('    }')
html_lines.append('    .star-btn:hover {')
html_lines.append('      transform: scale(1.2);')
html_lines.append('    }')
html_lines.append('    .star-active {')
html_lines.append('      color: #facc15 !important;')
html_lines.append('    }')
html_lines.append('    .num-label {')
html_lines.append('      display: inline-block;')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      margin-left: 2px;')
html_lines.append('    }')
html_lines.append('    .td-kw {')
html_lines.append('      width: 22%;')
html_lines.append('      min-width: 140px;')
html_lines.append('      word-break: break-word;')
html_lines.append('    }')
html_lines.append('    .kw-badge {')
html_lines.append('      display: inline-block;')
html_lines.append('      font-size: 8.5pt;')
html_lines.append('      font-weight: 700;')
html_lines.append('      color: #38bdf8;')
html_lines.append('      background: #0f2744;')
html_lines.append('      border: 1px solid #0284c7;')
html_lines.append('      padding: 1px 6px;')
html_lines.append('      border-radius: 4px;')
html_lines.append('      margin-bottom: 3px;')
html_lines.append('    }')
html_lines.append('    .kw-name {')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fde047;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      line-height: 1.45;')
html_lines.append('    }')
html_lines.append('    .td-q {')
html_lines.append('      width: 36%;')
html_lines.append('      min-width: 200px;')
html_lines.append('      color: #f1f5f9;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      word-break: break-word;')
html_lines.append('      line-height: 1.6;')
html_lines.append('    }')
html_lines.append('    .td-ans {')
html_lines.append('      width: 37%;')
html_lines.append('      min-width: 210px;')
html_lines.append('      color: #fef08a;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      font-weight: 600;')
html_lines.append('      word-break: break-word;')
html_lines.append('      line-height: 1.6;')
html_lines.append('      cursor: pointer;')
html_lines.append('      user-select: text;')
html_lines.append('    }')
html_lines.append('    .blind-mode .td-ans-content {')
html_lines.append('      filter: blur(6px);')
html_lines.append('      transition: filter 0.2s;')
html_lines.append('    }')
html_lines.append('    .blind-mode .td-ans:hover .td-ans-content,')
html_lines.append('    .blind-mode .td-ans.revealed .td-ans-content {')
html_lines.append('      filter: none;')
html_lines.append('    }')
html_lines.append('    .card-view-container {')
html_lines.append('      display: none;')
html_lines.append('      max-width: 720px;')
html_lines.append('      margin: 0 auto;')
html_lines.append('    }')
html_lines.append('    .card-controller {')
html_lines.append('      background: #161a23;')
html_lines.append('      border: 1px solid #2d3748;')
html_lines.append('      border-radius: 10px;')
html_lines.append('      padding: 12px 18px;')
html_lines.append('      display: flex;')
html_lines.append('      justify-content: space-between;')
html_lines.append('      align-items: center;')
html_lines.append('      margin-bottom: 16px;')
html_lines.append('      flex-wrap: wrap;')
html_lines.append('      gap: 10px;')
html_lines.append('    }')
html_lines.append('    .card-progress {')
html_lines.append('      font-size: 0.95rem;')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fbbf24;')
html_lines.append('    }')
html_lines.append('    .flashcard-wrap {')
html_lines.append('      perspective: 1200px;')
html_lines.append('      width: 100%;')
html_lines.append('      min-height: 380px;')
html_lines.append('      cursor: pointer;')
html_lines.append('    }')
html_lines.append('    .flashcard {')
html_lines.append('      position: relative;')
html_lines.append('      width: 100%;')
html_lines.append('      min-height: 380px;')
html_lines.append('      transition: transform 0.45s cubic-bezier(0.4, 0, 0.2, 1);')
html_lines.append('      transform-style: preserve-3d;')
html_lines.append('      border-radius: 16px;')
html_lines.append('    }')
html_lines.append('    .flashcard.flipped {')
html_lines.append('      transform: rotateY(180deg);')
html_lines.append('    }')
html_lines.append('    .card-face {')
html_lines.append('      position: absolute;')
html_lines.append('      top: 0;')
html_lines.append('      left: 0;')
html_lines.append('      width: 100%;')
html_lines.append('      height: 100%;')
html_lines.append('      min-height: 380px;')
html_lines.append('      backface-visibility: hidden;')
html_lines.append('      -webkit-backface-visibility: hidden;')
html_lines.append('      border-radius: 16px;')
html_lines.append('      padding: 28px 24px;')
html_lines.append('      display: flex;')
html_lines.append('      flex-direction: column;')
html_lines.append('      justify-content: space-between;')
html_lines.append('      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);')
html_lines.append('    }')
html_lines.append('    .card-front {')
html_lines.append('      background: #141824;')
html_lines.append('      border: 2px solid #2d3748;')
html_lines.append('    }')
html_lines.append('    .card-back {')
html_lines.append('      background: #1a1e2e;')
html_lines.append('      border: 2px solid #d97706;')
html_lines.append('      transform: rotateY(180deg);')
html_lines.append('    }')
html_lines.append('    .card-top {')
html_lines.append('      display: flex;')
html_lines.append('      justify-content: space-between;')
html_lines.append('      align-items: center;')
html_lines.append('      border-bottom: 1px solid #283042;')
html_lines.append('      padding-bottom: 12px;')
html_lines.append('      margin-bottom: 16px;')
html_lines.append('    }')
html_lines.append('    .card-main {')
html_lines.append('      flex: 1;')
html_lines.append('      display: flex;')
html_lines.append('      flex-direction: column;')
html_lines.append('      justify-content: center;')
html_lines.append('    }')
html_lines.append('    .card-prompt-label {')
html_lines.append('      font-size: 0.85rem;')
html_lines.append('      font-weight: 700;')
html_lines.append('      color: #94a3b8;')
html_lines.append('      margin-bottom: 10px;')
html_lines.append('      display: flex;')
html_lines.append('      align-items: center;')
html_lines.append('      gap: 6px;')
html_lines.append('    }')
html_lines.append('    .card-question {')
html_lines.append('      font-size: 1.12rem;')
html_lines.append('      color: #f1f5f9;')
html_lines.append('      line-height: 1.7;')
html_lines.append('      word-break: break-word;')
html_lines.append('    }')
html_lines.append('    .card-kw-title {')
html_lines.append('      font-size: 1.25rem;')
html_lines.append('      font-weight: 900;')
html_lines.append('      color: #fde047;')
html_lines.append('      margin-bottom: 14px;')
html_lines.append('      line-height: 1.4;')
html_lines.append('      word-break: break-word;')
html_lines.append('    }')
html_lines.append('    .card-answer {')
html_lines.append('      font-size: 1.05rem;')
html_lines.append('      color: #fef08a;')
html_lines.append('      font-weight: 600;')
html_lines.append('      line-height: 1.7;')
html_lines.append('      word-break: break-word;')
html_lines.append('    }')
html_lines.append('    .card-bottom-hint {')
html_lines.append('      text-align: center;')
html_lines.append('      font-size: 0.84rem;')
html_lines.append('      color: #64748b;')
html_lines.append('      border-top: 1px solid #283042;')
html_lines.append('      padding-top: 10px;')
html_lines.append('      margin-top: 16px;')
html_lines.append('    }')
html_lines.append('    .card-nav {')
html_lines.append('      display: flex;')
html_lines.append('      justify-content: center;')
html_lines.append('      align-items: center;')
html_lines.append('      gap: 12px;')
html_lines.append('      margin-top: 20px;')
html_lines.append('    }')
html_lines.append('    .btn-card-nav {')
html_lines.append('      background: #1e2536;')
html_lines.append('      color: #f1f5f9;')
html_lines.append('      border: 1px solid #334155;')
html_lines.append('      padding: 10px 20px;')
html_lines.append('      border-radius: 8px;')
html_lines.append('      font-size: 0.95rem;')
html_lines.append('      font-weight: 800;')
html_lines.append('      cursor: pointer;')
html_lines.append('      transition: background 0.2s;')
html_lines.append('    }')
html_lines.append('    .btn-card-nav:hover {')
html_lines.append('      background: #2d3748;')
html_lines.append('    }')
html_lines.append('    body.light-theme {')
html_lines.append('      background: #f8fafc;')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme .app-header {')
html_lines.append('      background: #0f172a;')
html_lines.append('      border-color: #334155;')
html_lines.append('    }')
html_lines.append('    body.light-theme .bar-title {')
html_lines.append('      color: #38bdf8;')
html_lines.append('    }')
html_lines.append('    body.light-theme .bar-sub {')
html_lines.append('      color: #cbd5e1;')
html_lines.append('    }')
html_lines.append('    body.light-theme .table-container {')
html_lines.append('      background: #ffffff;')
html_lines.append('      border-color: #cbd5e1;')
html_lines.append('    }')
html_lines.append('    body.light-theme .table-info-bar {')
html_lines.append('      background: #f1f5f9;')
html_lines.append('      color: #0f172a;')
html_lines.append('      border-bottom: 2px solid #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme table {')
html_lines.append('      background: #ffffff;')
html_lines.append('    }')
html_lines.append('    body.light-theme thead, body.light-theme th {')
html_lines.append('      background: #1e293b;')
html_lines.append('      color: #ffffff;')
html_lines.append('      border-color: #334155;')
html_lines.append('    }')
html_lines.append('    body.light-theme td {')
html_lines.append('      border-color: #cbd5e1;')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme tr:nth-child(even) {')
html_lines.append('      background: #f8fafc;')
html_lines.append('    }')
html_lines.append('    body.light-theme tr:nth-child(odd) {')
html_lines.append('      background: #ffffff;')
html_lines.append('    }')
html_lines.append('    body.light-theme tr:hover {')
html_lines.append('      background: #f1f5f9;')
html_lines.append('    }')
html_lines.append('    body.light-theme .num-label {')
html_lines.append('      color: #0284c7;')
html_lines.append('    }')
html_lines.append('    body.light-theme .kw-badge {')
html_lines.append('      background: #e0f2fe;')
html_lines.append('      color: #1e40af;')
html_lines.append('      border-color: #bae6fd;')
html_lines.append('    }')
html_lines.append('    body.light-theme .kw-name {')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme .td-q {')
html_lines.append('      color: #334155;')
html_lines.append('    }')
html_lines.append('    body.light-theme .td-ans {')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme .card-front {')
html_lines.append('      background: #ffffff;')
html_lines.append('      border-color: #cbd5e1;')
html_lines.append('    }')
html_lines.append('    body.light-theme .card-back {')
html_lines.append('      background: #f8fafc;')
html_lines.append('      border-color: #0284c7;')
html_lines.append('    }')
html_lines.append('    body.light-theme .card-question {')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme .card-kw-title {')
html_lines.append('      color: #0284c7;')
html_lines.append('    }')
html_lines.append('    body.light-theme .card-answer {')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme .card-controller {')
html_lines.append('      background: #f1f5f9;')
html_lines.append('      border-color: #cbd5e1;')
html_lines.append('    }')
html_lines.append('    body.light-theme .card-progress {')
html_lines.append('      color: #0284c7;')
html_lines.append('    }')
html_lines.append('    @media (max-width: 768px) {')
html_lines.append('      body {')
html_lines.append('        padding: 10px 6px;')
html_lines.append('      }')
html_lines.append('      .app-header {')
html_lines.append('        padding: 12px 14px;')
html_lines.append('      }')
html_lines.append('      .bar-title {')
html_lines.append('        font-size: 1.05rem;')
html_lines.append('      }')
html_lines.append('      .btn-action {')
html_lines.append('        padding: 6px 10px;')
html_lines.append('        font-size: 0.82rem;')
html_lines.append('      }')
html_lines.append('      td, th {')
html_lines.append('        font-size: 9.5pt;')
html_lines.append('        padding: 8px 8px;')
html_lines.append('      }')
html_lines.append('      .flashcard-wrap, .flashcard, .card-face {')
html_lines.append('        min-height: 340px;')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('    @media print {')
html_lines.append('      @page {')
html_lines.append('        size: A4 portrait;')
html_lines.append('        margin: 12mm 10mm 12mm 10mm;')
html_lines.append('      }')
html_lines.append('      body {')
html_lines.append('        background: #ffffff !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('        padding: 0 !important;')
html_lines.append('        font-family: "Malgun Gothic", "맑은 고딕", sans-serif !important;')
html_lines.append('      }')
html_lines.append('      .no-print-bar, .app-header, .card-view-container {')
html_lines.append('        display: none !important;')
html_lines.append('      }')
html_lines.append('      .table-container {')
html_lines.append('        display: block !important;')
html_lines.append('        max-width: 100% !important;')
html_lines.append('        box-shadow: none !important;')
html_lines.append('        border: none !important;')
html_lines.append('        border-radius: 0 !important;')
html_lines.append('        margin: 0 !important;')
html_lines.append('        background: #ffffff !important;')
html_lines.append('      }')
html_lines.append('      .table-info-bar {')
html_lines.append('        border-bottom: 2px solid #000000 !important;')
html_lines.append('        padding: 6px 4px !important;')
html_lines.append('        font-size: 9.5pt !important;')
html_lines.append('        background: #f1f5f9 !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      table {')
html_lines.append('        width: 100% !important;')
html_lines.append('        border-collapse: collapse !important;')
html_lines.append('        font-size: 10pt !important;')
html_lines.append('        background: #ffffff !important;')
html_lines.append('      }')
html_lines.append('      thead {')
html_lines.append('        display: table-header-group !important;')
html_lines.append('      }')
html_lines.append('      tbody {')
html_lines.append('        display: table-row-group !important;')
html_lines.append('      }')
html_lines.append('      tr {')
html_lines.append('        page-break-inside: avoid !important;')
html_lines.append('        break-inside: avoid !important;')
html_lines.append('      }')
html_lines.append('      th {')
html_lines.append('        background: #f1f5f9 !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('        border: 1px solid #94a3b8 !important;')
html_lines.append('        font-size: 10pt !important;')
html_lines.append('        padding: 6px 5px !important;')
html_lines.append('      }')
html_lines.append('      td {')
html_lines.append('        border: 1px solid #cbd5e1 !important;')
html_lines.append('        font-size: 10pt !important;')
html_lines.append('        padding: 6px 8px !important;')
html_lines.append('        line-height: 1.45 !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      .kw-name {')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      .num-label {')
html_lines.append('        color: #0284c7 !important;')
html_lines.append('      }')
html_lines.append('      .star-btn {')
html_lines.append('        display: none !important;')
html_lines.append('      }')
html_lines.append('      .td-q {')
html_lines.append('        color: #334155 !important;')
html_lines.append('      }')
html_lines.append('      .td-ans {')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      .td-ans-content {')
html_lines.append('        filter: none !important;')
html_lines.append('      }')
html_lines.append('      tr:nth-child(even) {')
html_lines.append('        background: #f8fafc !important;')
html_lines.append('      }')
html_lines.append('      tr:nth-child(odd) {')
html_lines.append('        background: #ffffff !important;')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('  </style>')
html_lines.append('</head>')
html_lines.append('<body>')
html_lines.append('')
html_lines.append('  <div class="app-header">')
html_lines.append('    <div>')
html_lines.append('      <div class="bar-title">🏛️ 2027 KICE 전문상담 1~200 핵심 표제어 마스터</div>')
html_lines.append('      <div class="bar-sub">아이케어 웜다크 · 맑은 고딕 10pt · 모바일/태블릿 반응형 · 카드뒤집기 · 별표암기함</div>')
html_lines.append('    </div>')
html_lines.append('    <div class="btn-group">')
html_lines.append('      <button id="btnModeTable" class="btn-action btn-active" onclick="switchView(\'table\')">📋 연속 표 보기</button>')
html_lines.append('      <button id="btnModeCard" class="btn-action" onclick="switchView(\'card\')">🎴 카드 뒤집기</button>')
html_lines.append('      <button id="btnStarFilter" class="btn-action btn-star-filter" onclick="toggleStarFilter()">⭐ 별표 모아보기 (<span id="starBadgeCount">0</span>)</button>')
html_lines.append('      <button id="btnBlindToggle" class="btn-action" onclick="toggleBlindMode()">👁️ 정답 가리기</button>')
html_lines.append('      <button id="btnThemeToggle" class="btn-action" onclick="toggleTheme()">☀️ 라이트 모드</button>')
html_lines.append('      <button class="btn-action" onclick="window.print()">🖨️ A4 인쇄</button>')
html_lines.append('      <a href="index.html" class="btn-action">🏠 모의고사 홈</a>')
html_lines.append('    </div>')
html_lines.append('  </div>')
html_lines.append('')
html_lines.append('  <div class="main-container">')
html_lines.append('')
html_lines.append('    <!-- Table View -->')
html_lines.append('    <div id="tableView" class="table-container">')
html_lines.append('      <div class="table-info-bar">')
html_lines.append('        <span id="tableStatusTitle">📋 2027 임용고시 전문상담 4점 만점 공식 서술 정답 (총 200문항 풀세트)</span>')
html_lines.append('        <span>맑은 고딕 10pt / 탭하여 정답 확인 가능</span>')
html_lines.append('      </div>')
html_lines.append('      <table>')
html_lines.append('        <thead>')
html_lines.append('          <tr>')
html_lines.append('            <th style="width: 60px;">No.</th>')
html_lines.append('            <th style="width: 22%;">영역 및 핵심 표제어</th>')
html_lines.append('            <th style="width: 36%;">❓ KICE 실전 힌트 박멸 문제 (단서)</th>')
html_lines.append('            <th style="width: 37%;">🏆 KICE 4점 만점 공식 서술 정답</th>')
html_lines.append('          </tr>')
html_lines.append('        </thead>')
html_lines.append('        <tbody id="tableBody">')
html_lines.append('        </tbody>')
html_lines.append('      </table>')
html_lines.append('    </div>')
html_lines.append('')
html_lines.append('    <!-- Flashcard View -->')
html_lines.append('    <div id="cardView" class="card-view-container">')
html_lines.append('      <div class="card-controller">')
html_lines.append('        <div class="card-progress">')
html_lines.append('          <span id="cardCounter">카드 1 / 200</span>')
html_lines.append('          <span id="cardFilterNotice" style="font-size: 0.8rem; color: #38bdf8; margin-left: 6px;"></span>')
html_lines.append('        </div>')
html_lines.append('        <div style="display: flex; gap: 8px;">')
html_lines.append('          <button class="btn-action" onclick="toggleCardStar()">⭐ 이 카드 별표</button>')
html_lines.append('          <button class="btn-action" onclick="shuffleCards()">🔀 무작위 섞기</button>')
html_lines.append('        </div>')
html_lines.append('      </div>')
html_lines.append('')
html_lines.append('      <div class="flashcard-wrap" onclick="flipCard()">')
html_lines.append('        <div id="activeCard" class="flashcard">')
html_lines.append('          <!-- Front -->')
html_lines.append('          <div class="card-face card-front">')
html_lines.append('            <div class="card-top">')
html_lines.append('              <div>')
html_lines.append('                <span id="cardFrontBadge" class="kw-badge">교육과정</span>')
html_lines.append('                <span id="cardFrontNum" class="num-label" style="font-size: 1.05rem;">No. 1</span>')
html_lines.append('              </div>')
html_lines.append('              <span id="cardFrontStar" style="font-size: 1.3rem; color: #64748b;">☆</span>')
html_lines.append('            </div>')
html_lines.append('            <div class="card-main">')
html_lines.append('              <div class="card-prompt-label">❓ KICE 실전 힌트 박멸 문제 (단서)</div>')
html_lines.append('              <div id="cardFrontQuestion" class="card-question"></div>')
html_lines.append('            </div>')
html_lines.append('            <div class="card-bottom-hint">👆 카드를 터치하면 만점 정답과 핵심 표제어가 뒤집힙니다</div>')
html_lines.append('          </div>')
html_lines.append('          <!-- Back -->')
html_lines.append('          <div class="card-face card-back">')
html_lines.append('            <div class="card-top">')
html_lines.append('              <div>')
html_lines.append('                <span id="cardBackBadge" class="kw-badge">교육과정</span>')
html_lines.append('                <span id="cardBackNum" class="num-label" style="font-size: 1.05rem;">No. 1</span>')
html_lines.append('              </div>')
html_lines.append('              <span id="cardBackStar" style="font-size: 1.3rem; color: #64748b;">☆</span>')
html_lines.append('            </div>')
html_lines.append('            <div class="card-main">')
html_lines.append('              <div class="card-prompt-label" style="color: #fbbf24;">🏆 KICE 공인 핵심 표제어</div>')
html_lines.append('              <div id="cardBackKw" class="card-kw-title"></div>')
html_lines.append('              <div class="card-prompt-label" style="color: #fbbf24; margin-top: 12px;">🏆 KICE 4점 만점 공식 서술 정답</div>')
html_lines.append('              <div id="cardBackAns" class="card-answer"></div>')
html_lines.append('            </div>')
html_lines.append('            <div class="card-bottom-hint">👆 다시 터치하면 문제로 뒤집힙니다</div>')
html_lines.append('          </div>')
html_lines.append('        </div>')
html_lines.append('      </div>')
html_lines.append('')
html_lines.append('      <div class="card-nav">')
html_lines.append('        <button class="btn-card-nav" onclick="prevCard()">◀ 이전 카드</button>')
html_lines.append('        <button class="btn-card-nav" onclick="flipCard()">🔄 뒤집기</button>')
html_lines.append('        <button class="btn-card-nav" onclick="nextCard()">다음 카드 ▶</button>')
html_lines.append('      </div>')
html_lines.append('    </div>')
html_lines.append('')
html_lines.append('  </div>')
html_lines.append('')
html_lines.append('  <script>')
items_json_str = json.dumps(all_200, ensure_ascii=False)
html_lines.append(f'    var DATA = {items_json_str};')
html_lines.append('    var starredIds = {};')
html_lines.append('    try {')
html_lines.append('      var saved = localStorage.getItem("kice_200_starred");')
html_lines.append('      if (saved) { starredIds = JSON.parse(saved); }')
html_lines.append('    } catch(e) {}')
html_lines.append('')
html_lines.append('    var starFilterActive = false;')
html_lines.append('    var blindModeActive = false;')
html_lines.append('    var currentCardList = [];')
html_lines.append('    var currentCardIdx = 0;')
html_lines.append('')
html_lines.append('    function saveStars() {')
html_lines.append('      try { localStorage.setItem("kice_200_starred", JSON.stringify(starredIds)); } catch(e) {}')
html_lines.append('      updateStarBadge();')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function updateStarBadge() {')
html_lines.append('      var count = 0;')
html_lines.append('      for (var k in starredIds) { if (starredIds[k]) count++; }')
html_lines.append('      var badge = document.getElementById("starBadgeCount");')
html_lines.append('      if (badge) badge.innerText = count;')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function toggleStar(id, ev) {')
html_lines.append('      if (ev) ev.stopPropagation();')
html_lines.append('      if (starredIds[id]) {')
html_lines.append('        delete starredIds[id];')
html_lines.append('      } else {')
html_lines.append('        starredIds[id] = true;')
html_lines.append('      }')
html_lines.append('      saveStars();')
html_lines.append('      renderTable();')
html_lines.append('      renderActiveCard();')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function renderTable() {')
html_lines.append('      var tbody = document.getElementById("tableBody");')
html_lines.append('      if (!tbody) return;')
html_lines.append('      var html = "";')
html_lines.append('      var visibleCount = 0;')
html_lines.append('      for (var i = 0; i < DATA.length; i++) {')
html_lines.append('        var it = DATA[i];')
html_lines.append('        var isStarred = !!starredIds[it.num];')
html_lines.append('        if (starFilterActive && !isStarred) continue;')
html_lines.append('        visibleCount++;')
html_lines.append('        var starChar = isStarred ? "★" : "☆";')
html_lines.append('        var starCls = isStarred ? "star-btn star-active" : "star-btn";')
html_lines.append('        html += "<tr>";')
html_lines.append('        html += "<td class=\'td-star-num\'>";')
html_lines.append('        html += "<button class=\'" + starCls + "\' onclick=\'toggleStar(" + it.num + ", event)\' title=\'중요 별표 등록\'>" + starChar + "</button>";')
html_lines.append('        html += "<span class=\'num-label\'>" + it.num + "</span>";')
html_lines.append('        html += "</td>";')
html_lines.append('        html += "<td class=\'td-kw\'>";')
html_lines.append('        html += "<span class=\'kw-badge\'>" + it.badge + "</span>";')
html_lines.append('        html += "<div class=\'kw-name\'>" + it.kw + "</div>";')
html_lines.append('        html += "</td>";')
html_lines.append('        html += "<td class=\'td-q\'>" + it.q + "</td>";')
html_lines.append('        html += "<td class=\'td-ans\' onclick=\'toggleRowReveal(this)\' title=\'터치하여 정답 확인\'>";')
html_lines.append('        html += "<div class=\'td-ans-content\'>" + it.ans + "</div>";')
html_lines.append('        html += "</td>";')
html_lines.append('        html += "</tr>";')
html_lines.append('      }')
html_lines.append('      tbody.innerHTML = html;')
html_lines.append('      var title = document.getElementById("tableStatusTitle");')
html_lines.append('      if (title) {')
html_lines.append('        if (starFilterActive) {')
html_lines.append('          title.innerText = "⭐ 중요 별표 등록 문항 모아보기 (" + visibleCount + "문항)";')
html_lines.append('        } else {')
html_lines.append('          title.innerText = "📋 2027 임용고시 전문상담 4점 만점 공식 서술 정답 (총 200문항 풀세트)";')
html_lines.append('        }')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function toggleRowReveal(tdElem) {')
html_lines.append('      if (blindModeActive) {')
html_lines.append('        tdElem.classList.toggle("revealed");')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function toggleBlindMode() {')
html_lines.append('      blindModeActive = !blindModeActive;')
html_lines.append('      var tableContainer = document.getElementById("tableView");')
html_lines.append('      var btn = document.getElementById("btnBlindToggle");')
html_lines.append('      if (blindModeActive) {')
html_lines.append('        tableContainer.classList.add("blind-mode");')
html_lines.append('        btn.classList.add("btn-active");')
html_lines.append('        btn.innerText = "👁️ 정답 보기 (가림 해제)";')
html_lines.append('      } else {')
html_lines.append('        tableContainer.classList.remove("blind-mode");')
html_lines.append('        btn.classList.remove("btn-active");')
html_lines.append('        btn.innerText = "👁️ 정답 가리기";')
html_lines.append('        var revealed = document.querySelectorAll(".revealed");')
html_lines.append('        for (var i = 0; i < revealed.length; i++) { revealed[i].classList.remove("revealed"); }')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function toggleStarFilter() {')
html_lines.append('      starFilterActive = !starFilterActive;')
html_lines.append('      var btn = document.getElementById("btnStarFilter");')
html_lines.append('      if (starFilterActive) {')
html_lines.append('        btn.classList.add("btn-active");')
html_lines.append('      } else {')
html_lines.append('        btn.classList.remove("btn-active");')
html_lines.append('      }')
html_lines.append('      renderTable();')
html_lines.append('      prepareCardList();')
html_lines.append('      renderActiveCard();')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function switchView(mode) {')
html_lines.append('      var tblView = document.getElementById("tableView");')
html_lines.append('      var crdView = document.getElementById("cardView");')
html_lines.append('      var btnTbl = document.getElementById("btnModeTable");')
html_lines.append('      var btnCrd = document.getElementById("btnModeCard");')
html_lines.append('      if (mode === "card") {')
html_lines.append('        tblView.style.display = "none";')
html_lines.append('        crdView.style.display = "block";')
html_lines.append('        btnCrd.classList.add("btn-active");')
html_lines.append('        btnTbl.classList.remove("btn-active");')
html_lines.append('        prepareCardList();')
html_lines.append('        renderActiveCard();')
html_lines.append('      } else {')
html_lines.append('        tblView.style.display = "block";')
html_lines.append('        crdView.style.display = "none";')
html_lines.append('        btnTbl.classList.add("btn-active");')
html_lines.append('        btnCrd.classList.remove("btn-active");')
html_lines.append('        renderTable();')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function prepareCardList() {')
html_lines.append('      currentCardList = [];')
html_lines.append('      for (var i = 0; i < DATA.length; i++) {')
html_lines.append('        var it = DATA[i];')
html_lines.append('        if (starFilterActive && !starredIds[it.num]) continue;')
html_lines.append('        currentCardList.push(it);')
html_lines.append('      }')
html_lines.append('      if (currentCardIdx >= currentCardList.length) {')
html_lines.append('        currentCardIdx = 0;')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function renderActiveCard() {')
html_lines.append('      var cardElem = document.getElementById("activeCard");')
html_lines.append('      if (cardElem) cardElem.classList.remove("flipped");')
html_lines.append('      if (currentCardList.length === 0) {')
html_lines.append('        document.getElementById("cardFrontBadge").innerText = "안내";')
html_lines.append('        document.getElementById("cardFrontNum").innerText = "-";')
html_lines.append('        document.getElementById("cardFrontQuestion").innerText = "별표 등록된 문항이 없습니다. 표나 카드에서 ⭐을 눌러 중요 문항을 등록해 보세요!";')
html_lines.append('        document.getElementById("cardCounter").innerText = "0 / 0";')
html_lines.append('        return;')
html_lines.append('      }')
html_lines.append('      var it = currentCardList[currentCardIdx];')
html_lines.append('      var isStarred = !!starredIds[it.num];')
html_lines.append('      var starChar = isStarred ? "★" : "☆";')
html_lines.append('      var starColor = isStarred ? "#facc15" : "#64748b";')
html_lines.append('      document.getElementById("cardFrontBadge").innerText = it.badge;')
html_lines.append('      document.getElementById("cardFrontNum").innerText = "No. " + it.num;')
html_lines.append('      var fStar = document.getElementById("cardFrontStar");')
html_lines.append('      fStar.innerText = starChar;')
html_lines.append('      fStar.style.color = starColor;')
html_lines.append('      document.getElementById("cardFrontQuestion").innerText = it.q;')
html_lines.append('      document.getElementById("cardBackBadge").innerText = it.badge;')
html_lines.append('      document.getElementById("cardBackNum").innerText = "No. " + it.num;')
html_lines.append('      var bStar = document.getElementById("cardBackStar");')
html_lines.append('      bStar.innerText = starChar;')
html_lines.append('      bStar.style.color = starColor;')
html_lines.append('      document.getElementById("cardBackKw").innerText = it.kw;')
html_lines.append('      document.getElementById("cardBackAns").innerText = it.ans;')
html_lines.append('      var curPos = currentCardIdx + 1;')
html_lines.append('      document.getElementById("cardCounter").innerText = "카드 " + curPos + " / " + currentCardList.length;')
html_lines.append('      var notice = document.getElementById("cardFilterNotice");')
html_lines.append('      if (starFilterActive) {')
html_lines.append('        notice.innerText = "(⭐ 별표 문항 모음)";')
html_lines.append('      } else {')
html_lines.append('        notice.innerText = "";')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function flipCard() {')
html_lines.append('      var cardElem = document.getElementById("activeCard");')
html_lines.append('      if (cardElem) cardElem.classList.toggle("flipped");')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function prevCard() {')
html_lines.append('      if (currentCardList.length === 0) return;')
html_lines.append('      currentCardIdx--;')
html_lines.append('      if (currentCardIdx < 0) currentCardIdx = currentCardList.length - 1;')
html_lines.append('      renderActiveCard();')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function nextCard() {')
html_lines.append('      if (currentCardList.length === 0) return;')
html_lines.append('      currentCardIdx++;')
html_lines.append('      if (currentCardIdx >= currentCardList.length) currentCardIdx = 0;')
html_lines.append('      renderActiveCard();')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function toggleCardStar() {')
html_lines.append('      if (currentCardList.length === 0) return;')
html_lines.append('      var it = currentCardList[currentCardIdx];')
html_lines.append('      toggleStar(it.num);')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function shuffleCards() {')
html_lines.append('      currentCardList.sort(function() { return Math.random() - 0.5; });')
html_lines.append('      currentCardIdx = 0;')
html_lines.append('      renderActiveCard();')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    function toggleTheme() {')
html_lines.append('      var b = document.body;')
html_lines.append('      var btn = document.getElementById("btnThemeToggle");')
html_lines.append('      if (b.classList.contains("light-theme")) {')
html_lines.append('        b.classList.remove("light-theme");')
html_lines.append('        btn.innerText = "☀️ 라이트 모드";')
html_lines.append('      } else {')
html_lines.append('        b.classList.add("light-theme");')
html_lines.append('        btn.innerText = "🌙 웜다크 모드";')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('')
html_lines.append('    updateStarBadge();')
html_lines.append('    renderTable();')
html_lines.append('  </script>')
html_lines.append('</body>')
html_lines.append('</html>')

full_html = '\n'.join(html_lines)

# Strict Asterisk Check
if '*' in full_html:
    raise ValueError("Found asterisk in generated HTML!")

target_path = r'G:\내 드라이브\ANTI GRAVITY\전문상담임용고시\kice-300-wordbook\kice_150_core_table_a4.html'
with open(target_path, 'w', encoding='utf-8') as f:
    f.write(full_html)

print("Successfully written 200 items app to:", target_path)
print("File length in lines:", len(html_lines))
print("File size in bytes:", len(full_html.encode('utf-8')))
print("Zero asterisks strictly verified!")
