import json
import sys
import os

sys.path.insert(0, os.path.abspath('scratch'))
import generate_continuous_150 as gen_base

with open('scratch/items_150_raw.json', 'r', encoding='utf-8') as f:
    items = json.load(f)

refined_kws = gen_base.refined_kws
compact_answers = gen_base.compact_answers

html_lines = []
html_lines.append('<!DOCTYPE html>')
html_lines.append('<html lang="ko">')
html_lines.append('<head>')
html_lines.append('  <meta charset="UTF-8">')
html_lines.append('  <meta name="viewport" content="width=device-width, initial-scale=1.0">')
html_lines.append('  <title>2027 KICE 전문상담 1~150 핵심 표제어 연속 총정리 표 (아이케어 다크모드 / 맑은 고딕 10pt)</title>')
html_lines.append('  <style>')
html_lines.append('    @page {')
html_lines.append('      size: A4 portrait;')
html_lines.append('      margin: 12mm 10mm 12mm 10mm;')
html_lines.append('    }')
html_lines.append('    html, body, div, table, thead, tbody, tr, th, td, p, h1, h2, h3, span, button, a {')
html_lines.append('      box-sizing: border-box;')
html_lines.append('      margin: 0;')
html_lines.append('      padding: 0;')
html_lines.append('    }')
html_lines.append('    body {')
html_lines.append('      font-family: "Malgun Gothic", "맑은 고딕", "Apple SD Gothic Neo", sans-serif;')
html_lines.append('      background: #0f1117;')
html_lines.append('      color: #e2e8f0;')
html_lines.append('      line-height: 1.65;')
html_lines.append('      padding: 24px 16px;')
html_lines.append('      -webkit-font-smoothing: antialiased;')
html_lines.append('    }')
html_lines.append('    .no-print-bar {')
html_lines.append('      max-width: 1200px;')
html_lines.append('      margin: 0 auto 20px auto;')
html_lines.append('      background: #161a23;')
html_lines.append('      color: #f1f5f9;')
html_lines.append('      padding: 16px 24px;')
html_lines.append('      border-radius: 12px;')
html_lines.append('      border: 1px solid #2d3748;')
html_lines.append('      display: flex;')
html_lines.append('      justify-content: space-between;')
html_lines.append('      align-items: center;')
html_lines.append('      flex-wrap: wrap;')
html_lines.append('      gap: 14px;')
html_lines.append('      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);')
html_lines.append('    }')
html_lines.append('    .bar-title {')
html_lines.append('      font-size: 1.18rem;')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      display: flex;')
html_lines.append('      align-items: center;')
html_lines.append('      gap: 8px;')
html_lines.append('    }')
html_lines.append('    .bar-sub {')
html_lines.append('      font-size: 0.88rem;')
html_lines.append('      color: #94a3b8;')
html_lines.append('      margin-top: 4px;')
html_lines.append('    }')
html_lines.append('    .btn-group {')
html_lines.append('      display: flex;')
html_lines.append('      gap: 10px;')
html_lines.append('      align-items: center;')
html_lines.append('    }')
html_lines.append('    .btn-action {')
html_lines.append('      background: #fbbf24;')
html_lines.append('      color: #0f1117;')
html_lines.append('      border: 1px solid #f59e0b;')
html_lines.append('      padding: 10px 18px;')
html_lines.append('      border-radius: 8px;')
html_lines.append('      font-size: 0.95rem;')
html_lines.append('      font-weight: 800;')
html_lines.append('      cursor: pointer;')
html_lines.append('      text-decoration: none;')
html_lines.append('      display: inline-flex;')
html_lines.append('      align-items: center;')
html_lines.append('      gap: 6px;')
html_lines.append('      font-family: inherit;')
html_lines.append('      transition: background 0.2s;')
html_lines.append('    }')
html_lines.append('    .btn-action:hover {')
html_lines.append('      background: #f59e0b;')
html_lines.append('    }')
html_lines.append('    .btn-home {')
html_lines.append('      background: #1e2536;')
html_lines.append('      color: #e2e8f0;')
html_lines.append('      border-color: #334155;')
html_lines.append('    }')
html_lines.append('    .btn-home:hover {')
html_lines.append('      background: #2d3748;')
html_lines.append('    }')
html_lines.append('    .btn-theme {')
html_lines.append('      background: #1e2536;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      border-color: #d97706;')
html_lines.append('    }')
html_lines.append('    .btn-theme:hover {')
html_lines.append('      background: #2d3748;')
html_lines.append('    }')
html_lines.append('    .table-container {')
html_lines.append('      max-width: 1200px;')
html_lines.append('      margin: 0 auto;')
html_lines.append('      background: #11141d;')
html_lines.append('      border: 1.5px solid #2d3748;')
html_lines.append('      border-radius: 10px;')
html_lines.append('      box-shadow: 0 4px 24px rgba(0, 0, 0, 0.6);')
html_lines.append('      overflow: hidden;')
html_lines.append('    }')
html_lines.append('    .table-info-bar {')
html_lines.append('      background: #161b26;')
html_lines.append('      border-bottom: 2px solid #d97706;')
html_lines.append('      padding: 12px 20px;')
html_lines.append('      display: flex;')
html_lines.append('      justify-content: space-between;')
html_lines.append('      align-items: center;')
html_lines.append('      font-size: 0.92rem;')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fbbf24;')
html_lines.append('    }')
html_lines.append('    table {')
html_lines.append('      width: 100%;')
html_lines.append('      border-collapse: collapse;')
html_lines.append('      font-family: "Malgun Gothic", "맑은 고딕", "Apple SD Gothic Neo", sans-serif;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      background: #11141d;')
html_lines.append('    }')
html_lines.append('    thead {')
html_lines.append('      background: #161a24;')
html_lines.append('      position: sticky;')
html_lines.append('      top: 0;')
html_lines.append('      z-index: 20;')
html_lines.append('    }')
html_lines.append('    th {')
html_lines.append('      background: #161a24;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      border: 1px solid #283042;')
html_lines.append('      padding: 11px 8px;')
html_lines.append('      font-weight: 800;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      text-align: center;')
html_lines.append('      letter-spacing: -0.2px;')
html_lines.append('    }')
html_lines.append('    td {')
html_lines.append('      border: 1px solid #222938;')
html_lines.append('      padding: 10px 13px;')
html_lines.append('      vertical-align: top;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      line-height: 1.65;')
html_lines.append('      color: #e2e8f0;')
html_lines.append('    }')
html_lines.append('    tr:nth-child(even) {')
html_lines.append('      background: #141822;')
html_lines.append('    }')
html_lines.append('    tr:nth-child(odd) {')
html_lines.append('      background: #10131b;')
html_lines.append('    }')
html_lines.append('    tr:hover {')
html_lines.append('      background: #1e2433;')
html_lines.append('    }')
html_lines.append('    .td-num {')
html_lines.append('      width: 50px;')
html_lines.append('      text-align: center;')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fbbf24;')
html_lines.append('      font-size: 10pt;')
html_lines.append('    }')
html_lines.append('    .td-kw {')
html_lines.append('      width: 22%;')
html_lines.append('      word-break: keep-all;')
html_lines.append('    }')
html_lines.append('    .kw-badge {')
html_lines.append('      display: inline-block;')
html_lines.append('      font-size: 8.5pt;')
html_lines.append('      font-weight: 700;')
html_lines.append('      color: #38bdf8;')
html_lines.append('      background: #0f2744;')
html_lines.append('      border: 1px solid #0284c7;')
html_lines.append('      padding: 2px 6px;')
html_lines.append('      border-radius: 4px;')
html_lines.append('      margin-bottom: 4px;')
html_lines.append('    }')
html_lines.append('    .kw-name {')
html_lines.append('      font-weight: 800;')
html_lines.append('      color: #fde047;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      line-height: 1.5;')
html_lines.append('    }')
html_lines.append('    .td-q {')
html_lines.append('      width: 36%;')
html_lines.append('      color: #f1f5f9;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      word-break: keep-all;')
html_lines.append('      line-height: 1.65;')
html_lines.append('    }')
html_lines.append('    .td-ans {')
html_lines.append('      width: 37%;')
html_lines.append('      color: #fef08a;')
html_lines.append('      font-size: 10pt;')
html_lines.append('      font-weight: 600;')
html_lines.append('      word-break: keep-all;')
html_lines.append('      line-height: 1.65;')
html_lines.append('    }')

html_lines.append('    body.light-theme {')
html_lines.append('      background: #f8fafc;')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme .no-print-bar {')
html_lines.append('      background: #0f172a;')
html_lines.append('      border-color: #334155;')
html_lines.append('    }')
html_lines.append('    body.light-theme .bar-title {')
html_lines.append('      color: #38bdf8;')
html_lines.append('    }')
html_lines.append('    body.light-theme .bar-sub {')
html_lines.append('      color: #cbd5e1;')
html_lines.append('    }')
html_lines.append('    body.light-theme .btn-action {')
html_lines.append('      background: #0284c7;')
html_lines.append('      color: #ffffff;')
html_lines.append('      border-color: #38bdf8;')
html_lines.append('    }')
html_lines.append('    body.light-theme .table-container {')
html_lines.append('      background: #ffffff;')
html_lines.append('      border: 1.5px solid #cbd5e1;')
html_lines.append('    }')
html_lines.append('    body.light-theme .table-info-bar {')
html_lines.append('      background: #f1f5f9;')
html_lines.append('      color: #0f172a;')
html_lines.append('      border-bottom: 2px solid #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme table {')
html_lines.append('      background: #ffffff;')
html_lines.append('    }')
html_lines.append('    body.light-theme thead, body.light-theme th {')
html_lines.append('      background: #1e293b;')
html_lines.append('      color: #ffffff;')
html_lines.append('      border-color: #334155;')
html_lines.append('    }')
html_lines.append('    body.light-theme td {')
html_lines.append('      border-color: #cbd5e1;')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme tr:nth-child(even) {')
html_lines.append('      background: #f8fafc;')
html_lines.append('    }')
html_lines.append('    body.light-theme tr:nth-child(odd) {')
html_lines.append('      background: #ffffff;')
html_lines.append('    }')
html_lines.append('    body.light-theme tr:hover {')
html_lines.append('      background: #f1f5f9;')
html_lines.append('    }')
html_lines.append('    body.light-theme .td-num {')
html_lines.append('      color: #0284c7;')
html_lines.append('    }')
html_lines.append('    body.light-theme .kw-badge {')
html_lines.append('      background: #e0f2fe;')
html_lines.append('      color: #1e40af;')
html_lines.append('      border-color: #bae6fd;')
html_lines.append('    }')
html_lines.append('    body.light-theme .kw-name {')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    body.light-theme .td-q {')
html_lines.append('      color: #334155;')
html_lines.append('    }')
html_lines.append('    body.light-theme .td-ans {')
html_lines.append('      color: #0f172a;')
html_lines.append('    }')
html_lines.append('    @media print {')
html_lines.append('      @page {')
html_lines.append('        size: A4 portrait;')
html_lines.append('        margin: 12mm 10mm 12mm 10mm;')
html_lines.append('      }')
html_lines.append('      body {')
html_lines.append('        background: #ffffff !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('        padding: 0 !important;')
html_lines.append('        font-family: "Malgun Gothic", "맑은 고딕", sans-serif !important;')
html_lines.append('      }')
html_lines.append('      .no-print-bar {')
html_lines.append('        display: none !important;')
html_lines.append('      }')
html_lines.append('      .table-container {')
html_lines.append('        max-width: 100% !important;')
html_lines.append('        box-shadow: none !important;')
html_lines.append('        border: none !important;')
html_lines.append('        border-radius: 0 !important;')
html_lines.append('        margin: 0 !important;')
html_lines.append('        background: #ffffff !important;')
html_lines.append('      }')
html_lines.append('      .table-info-bar {')
html_lines.append('        border-bottom: 2px solid #000000 !important;')
html_lines.append('        padding: 6px 4px !important;')
html_lines.append('        font-size: 9.5pt !important;')
html_lines.append('        background: #f1f5f9 !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      table {')
html_lines.append('        width: 100% !important;')
html_lines.append('        border-collapse: collapse !important;')
html_lines.append('        font-size: 10pt !important;')
html_lines.append('        background: #ffffff !important;')
html_lines.append('      }')
html_lines.append('      thead {')
html_lines.append('        display: table-header-group !important;')
html_lines.append('      }')
html_lines.append('      tbody {')
html_lines.append('        display: table-row-group !important;')
html_lines.append('      }')
html_lines.append('      tr {')
html_lines.append('        page-break-inside: avoid !important;')
html_lines.append('        break-inside: avoid !important;')
html_lines.append('      }')
html_lines.append('      th {')
html_lines.append('        background: #f1f5f9 !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('        border: 1px solid #94a3b8 !important;')
html_lines.append('        font-size: 10pt !important;')
html_lines.append('        padding: 6px 5px !important;')
html_lines.append('      }')
html_lines.append('      td {')
html_lines.append('        border: 1px solid #cbd5e1 !important;')
html_lines.append('        font-size: 10pt !important;')
html_lines.append('        padding: 6px 8px !important;')
html_lines.append('        line-height: 1.45 !important;')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      .kw-name {')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      .td-num {')
html_lines.append('        color: #0284c7 !important;')
html_lines.append('      }')
html_lines.append('      .td-q {')
html_lines.append('        color: #334155 !important;')
html_lines.append('      }')
html_lines.append('      .td-ans {')
html_lines.append('        color: #000000 !important;')
html_lines.append('      }')
html_lines.append('      tr:nth-child(even) {')
html_lines.append('        background: #f8fafc !important;')
html_lines.append('      }')
html_lines.append('      tr:nth-child(odd) {')
html_lines.append('        background: #ffffff !important;')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('  </style>')
html_lines.append('</head>')
html_lines.append('<body>')
html_lines.append('')
html_lines.append('  <div class="no-print-bar">')
html_lines.append('    <div>')
html_lines.append('      <div class="bar-title">🏛️ 2027 KICE 전문상담 1~150 핵심 표제어 연속 총정리 표</div>')
html_lines.append('      <div class="bar-sub">아이케어(Eye-Care) 저자극 웜다크 모드 · 맑은 고딕 10pt · 빈칸 없는 완결형 1~150 테이블</div>')
html_lines.append('    </div>')
html_lines.append('    <div class="btn-group">')
html_lines.append('      <button id="themeToggleBtn" class="btn-action btn-theme" onclick="toggleTheme()">☀️ 라이트 모드로 전환</button>')
html_lines.append('      <a href="index.html" class="btn-action btn-home">🏠 모의고사 홈</a>')
html_lines.append('      <button class="btn-action" onclick="window.print()">🖨️ A4 바로 인쇄 / PDF 저장</button>')
html_lines.append('    </div>')
html_lines.append('  </div>')
html_lines.append('')
html_lines.append('  <div class="table-container">')
html_lines.append('    <div class="table-info-bar">')
html_lines.append('      <span>📋 2027 임용고시 전문상담 4점 만점 공식 서술 정답 총정리 (No. 1 ~ 150)</span>')
html_lines.append('      <span>KICE 공인 명칭·약어 / 맑은 고딕 10pt / 눈이 편안한 웜다크 배색</span>')
html_lines.append('    </div>')
html_lines.append('    <table>')
html_lines.append('      <thead>')
html_lines.append('        <tr>')
html_lines.append('          <th style="width: 55px;">No.</th>')
html_lines.append('          <th style="width: 22%;">영역 및 핵심 표제어</th>')
html_lines.append('          <th style="width: 36%;">❓ KICE 실전 힌트 박멸 문제 (단서)</th>')
html_lines.append('          <th style="width: 37%;">🏆 KICE 4점 만점 공식 서술 정답</th>')
html_lines.append('        </tr>')
html_lines.append('      </thead>')
html_lines.append('      <tbody>')

for it in items:
    num = it['num']
    badge = it['badge']
    kw = refined_kws.get(num, it['kw_name'])
    q = it['question']
    ans = compact_answers.get(num, it['answer'])
    
    html_lines.append('        <tr>')
    html_lines.append(f'          <td class="td-num">{num}</td>')
    html_lines.append('          <td class="td-kw">')
    html_lines.append(f'            <span class="kw-badge">{badge}</span>')
    html_lines.append(f'            <div class="kw-name">{kw}</div>')
    html_lines.append('          </td>')
    html_lines.append(f'          <td class="td-q">{q}</td>')
    html_lines.append(f'          <td class="td-ans">{ans}</td>')
    html_lines.append('        </tr>')

html_lines.append('      </tbody>')
html_lines.append('    </table>')
html_lines.append('  </div>')
html_lines.append('')
html_lines.append('  <script>')
html_lines.append('    function toggleTheme() {')
html_lines.append('      var b = document.body;')
html_lines.append('      var btn = document.getElementById("themeToggleBtn");')
html_lines.append('      if (b.classList.contains("light-theme")) {')
html_lines.append('        b.classList.remove("light-theme");')
html_lines.append('        btn.innerText = "☀️ 라이트 모드로 전환";')
html_lines.append('      } else {')
html_lines.append('        b.classList.add("light-theme");')
html_lines.append('        btn.innerText = "🌙 아이케어 웜다크 모드";')
html_lines.append('      }')
html_lines.append('    }')
html_lines.append('  </script>')
html_lines.append('</body>')
html_lines.append('</html>')

full_html = '\n'.join(html_lines)

# Strict Asterisk Check
if '*' in full_html:
    raise ValueError("Found asterisk in generated HTML!")

target_path = r'G:\내 드라이브\ANTI GRAVITY\전문상담임용고시\kice-300-wordbook\kice_150_core_table_a4.html'
with open(target_path, 'w', encoding='utf-8') as f:
    f.write(full_html)

print("Successfully written to:", target_path)
print("File length in lines:", len(html_lines))
print("File size in bytes:", len(full_html.encode('utf-8')))
print("Zero asterisks strictly verified!")
